# Generated by Django 4.2.16 on 2024-11-30 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchtimemanager',
            name='paused_time',
        ),
        migrations.RemoveField(
            model_name='matchtimemanager',
            name='resumed_time',
        ),
        migrations.RemoveField(
            model_name='matchtimemanager',
            name='total_elapsed_time',
        ),
        migrations.AddField(
            model_name='matchtimemanager',
            name='match_ended',
            field=models.BooleanField(default=False, help_text='Indicates whether the match has ended.'),
        ),
        migrations.CreateModel(
            name='MatchPauseResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paused_at', models.DateTimeField(help_text='The time when the match was paused.')),
                ('resumed_at', models.DateTimeField(blank=True, help_text='The time when the match resumed.', null=True)),
                ('match_time_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pause_resume_sessions', to='matchApp.matchtimemanager')),
            ],
        ),
    ]
