# Generated by Django 4.2.16 on 2024-12-02 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchApp', '0002_remove_matchtimemanager_paused_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchtimemanager',
            name='extra_time',
        ),
        migrations.AddField(
            model_name='matchtimemanager',
            name='extra_time_first_half',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='matchtimemanager',
            name='extra_time_full_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
