# Generated by Django 4.2.16 on 2024-12-04 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchApp', '0003_remove_matchtimemanager_extra_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchtimemanager',
            name='full_time_duration',
        ),
        migrations.RemoveField(
            model_name='matchtimemanager',
            name='half_time_interval',
        ),
        migrations.RemoveField(
            model_name='matchtimemanager',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='matchtimemanager',
            name='extra_time_first_half',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Extra time added after the first half.'),
        ),
        migrations.AlterField(
            model_name='matchtimemanager',
            name='extra_time_full_time',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Extra time added after the full-time duration.'),
        ),
    ]
