# Generated by Django 4.2.16 on 2024-12-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchApp', '0004_remove_matchtimemanager_full_time_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchtimemanager',
            name='match_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
