# Generated by Django 4.2.16 on 2024-12-06 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchApp', '0005_matchtimemanager_match_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchtimemanager',
            name='extra_time_first_half',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), help_text='Extra time added after the first half.', null=True),
        ),
        migrations.AlterField(
            model_name='matchtimemanager',
            name='extra_time_full_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), help_text='Extra time added after the full-time duration.', null=True),
        ),
    ]
