# Generated by Django 4.2.16 on 2024-12-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchApp', '0006_alter_matchtimemanager_extra_time_first_half_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchtimemanager',
            old_name='match_start_time',
            new_name='start_time',
        ),
    ]
