# Generated by Django 4.2.16 on 2024-12-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchApp', '0007_rename_match_start_time_matchtimemanager_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('Initiated', 'Initiated'), ('Ongoing', 'Ongoing'), ('Interrupted', 'Interrupted'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Scheduled', 'Scheduled'), ('Expired', 'Expired')], default='Initiated', max_length=20),
        ),
    ]
