# Generated by Django 4.2.16 on 2024-12-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchApp', '0008_alter_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='substitution',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
