# Generated by Django 4.2.16 on 2024-12-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchApp', '0009_substitution_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='substitution',
            old_name='previous_player',
            new_name='player_in',
        ),
        migrations.RenameField(
            model_name='substitution',
            old_name='new_player',
            new_name='player_out',
        ),
        migrations.RemoveField(
            model_name='substitution',
            name='team',
        ),
    ]
