# Generated by Django 4.2.16 on 2024-12-09 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchApp', '0010_rename_previous_player_substitution_player_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substitution',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchApp.match'),
        ),
    ]
