# Generated by Django 4.2.16 on 2024-12-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchApp', '0011_alter_substitution_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchpauseresume',
            name='is_before_half',
            field=models.BooleanField(default=False),
        ),
    ]
