# Generated by Django 4.2.16 on 2024-12-09 13:40

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matchApp', '0012_matchpauseresume_is_before_half'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchpauseresume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 9, 13, 40, 45, 864050, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchpauseresume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='matchtimemanager',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchtimemanager',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
