# Generated by Django 4.2.16 on 2024-12-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchApp', '0013_matchpauseresume_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchtimemanager',
            name='first_half_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchtimemanager',
            name='second_half_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
