# Generated by Django 4.2.16 on 2024-12-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchApp', '0014_matchtimemanager_first_half_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchtimemanager',
            name='first_half_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchtimemanager',
            name='second_half_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchtimemanager',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
