# Generated by Django 4.2.16 on 2024-12-13 19:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchApp', '0015_alter_matchtimemanager_first_half_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchpauseresume',
            name='match_time_manager',
        ),
        migrations.AddField(
            model_name='matchpauseresume',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pause_resume_sessions', to='matchApp.match'),
            preserve_default=False,
        ),
    ]
