# Generated by Django 4.2.16 on 2024-12-13 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchApp', '0017_alter_matchpauseresume_paused_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchpauseresume',
            name='paused_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 13, 19, 42, 48, 470453), help_text='The time when the match was paused.'),
        ),
    ]
