# Generated by Django 4.2.16 on 2024-12-13 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matchApp', '0018_alter_matchpauseresume_paused_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchpauseresume',
            name='paused_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The time when the match was paused.'),
        ),
    ]
