# Generated by Django 4.2.16 on 2024-12-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchApp', '0019_alter_matchpauseresume_paused_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStatics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='matchtimemanager',
            name='is_half_time_over',
            field=models.BooleanField(default=False),
        ),
    ]
