# Generated by Django 4.2.16 on 2025-01-09 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('matchApp', '0021_matchtimemanager_match_end_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fall',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fouls', to='team.player'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='team.player'),
        ),
        migrations.AlterField(
            model_name='playermatchevents',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.player'),
        ),
        migrations.AlterField(
            model_name='substitution',
            name='player_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_player_substitutions', to='team.player'),
        ),
        migrations.AlterField(
            model_name='substitution',
            name='player_out',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_player_substitutions', to='team.player'),
        ),
    ]
