# Generated by Django 4.2.7 on 2023-12-09 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiesheet',
            name='match_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='matchstatus',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sportsApp.tiesheet'),
        ),
    ]
