# Generated by Django 4.2.7 on 2023-12-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0002_tiesheet_match_complete_alter_matchstatus_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event_title', models.CharField(max_length=255)),
                ('event_description', models.TextField()),
                ('sport_type', models.CharField(choices=[('NATIONAL', 'National'), ('FOOTBALL', 'Football'), ('VOLLEYBALL', 'Volleyball'), ('TENNIS', 'Tennis'), ('GLOBAL', 'Global'), ('CIRCKET', 'Circket')], default='NATIONAL', max_length=25)),
            ],
        ),
    ]
