# Generated by Django 4.2.7 on 2024-07-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0004_latestnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
