# Generated by Django 4.2.7 on 2024-07-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0005_alter_latestnews_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestnews',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
