# Generated by Django 4.2.16 on 2024-11-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0005_rename_resistration_end_date_event_registration_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/events/'),
        ),
    ]
