# Generated by Django 4.2.16 on 2024-11-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0006_event_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Initiated', 'Initiated'), ('Registration', 'Registration'), ('Running', 'Running'), ('Interrupted', 'Interrupted'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Initiated', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('Initiated', 'Initiated'), ('Running', 'Running'), ('Interrupted', 'Interrupted'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Initiated', max_length=20),
        ),
    ]
