# Generated by Django 4.2.16 on 2024-11-13 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('sportsApp', '0008_alter_event_event_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='default_address',
            new_name='area',
        ),
        migrations.AddField(
            model_name='event',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.district'),
        ),
        migrations.AddField(
            model_name='event',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.municipality'),
        ),
        migrations.AddField(
            model_name='event',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.province'),
        ),
    ]
