# Generated by Django 4.2.7 on 2024-07-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0009_alter_player_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
