# Generated by Django 4.2.16 on 2024-11-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0010_alter_event_area_alter_event_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('League', 'League'), ('Knockout', 'Knockout'), ('Friendly', 'Friendly')], default='Knockout', max_length=20),
        ),
    ]
