# Generated by Django 4.2.16 on 2024-11-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0011_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventteam',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
