# Generated by Django 4.2.7 on 2024-07-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0011_team_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='sports_genere',
            field=models.CharField(blank=True, choices=[('FOOTBALL', 'Football')], default='FOOTBALL', max_length=25),
        ),
    ]
