# Generated by Django 4.2.16 on 2024-11-14 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('sportsApp', '0012_eventteam_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.district'),
        ),
        migrations.AddField(
            model_name='team',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.municipality'),
        ),
        migrations.AddField(
            model_name='team',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.province'),
        ),
    ]
