# Generated by Django 4.2.7 on 2024-07-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0012_alter_team_sports_genere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
