# Generated by Django 4.2.7 on 2024-07-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0014_player_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
