# Generated by Django 4.2.16 on 2024-11-28 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0015_match_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='team',
        ),
    ]
