# Generated by Django 4.2.16 on 2024-11-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0016_remove_goal_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
