# Generated by Django 4.2.7 on 2024-07-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0016_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='designation',
            field=models.CharField(blank=True, choices=[('GK', 'Goalkeeper'), ('RB', 'Right Back'), ('LB', 'Left Back'), ('CB', 'Center Back'), ('DM', 'Defensive Midfielder'), ('CM', 'Central Midfielder'), ('AM', 'Attacking Midfielder'), ('RM', 'Right Midfielder'), ('LM', 'Left Midfielder'), ('RW', 'Right Winger'), ('LW', 'Left Winger'), ('FW', 'Forward'), ('ST', 'Striker')], max_length=100, null=True),
        ),
    ]
