# Generated by Django 4.2.7 on 2024-07-27 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0018_team_banner_team_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='images/events/')),
                ('title', models.CharField(max_length=255)),
                ('event_age_limit', models.PositiveIntegerField()),
                ('is_verified', models.BooleanField(default=False)),
                ('entry_fee', models.DecimalField(decimal_places=3, max_digits=10000)),
                ('registration_start_date', models.DateField()),
                ('resistration_end_date', models.DateField()),
                ('event_start_date', models.DateTimeField(blank=True, null=True)),
                ('event_end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='gender',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='recentevents',
            name='sport_type',
            field=models.CharField(choices=[('FOOTBALL', 'Football')], default='FOOTBALL', max_length=25),
        ),
        migrations.CreateModel(
            name='TeamStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_match_played', models.PositiveIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sportsApp.team')),
            ],
        ),
        migrations.CreateModel(
            name='Sponser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sponser_type', models.CharField(choices=[('PLATFORM_SPONSERS', 1), ('EVENT_SPONSERS', 2)], max_length=25)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/sponsers/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sportsApp.event')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_match_played', models.PositiveIntegerField()),
                ('total_goals', models.PositiveIntegerField()),
                ('total_man_of_the_match', models.PositiveIntegerField()),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sportsApp.player')),
            ],
        ),
    ]
