# Generated by Django 4.2.7 on 2024-07-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0019_event_messages_subscriber_team_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrequest',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
