# Generated by Django 4.2.16 on 2024-11-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0019_remove_fall_team_alter_fall_player_alter_goal_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='fall',
            name='fall_category',
            field=models.CharField(choices=[('NORMAL_FALL', 'Normal Fall'), ('YELLOW_CARD', 'Yellow Card'), ('RED_CARD', 'Red Card')], default='NORMAL_FALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='fall',
            name='fall_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fall',
            name='fall_type',
            field=models.CharField(choices=[('HAND_BALL', 'Hand Ball'), ('OFFSIDE', 'Offside'), ('DANGEROUS_PLAY', 'Dangerous Play'), ('PUSHING', 'Pushing'), ('TRIPPING', 'Tripping'), ('UNSPORTING_BEHAVIOR', 'Unsporting Behavior'), ('OBSTRUCTION', 'Obstruction'), ('ILLEGAL_TACKLE', 'Illegal Tackle'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
