# Generated by Django 4.2.16 on 2024-11-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0020_fall_fall_category_alter_fall_fall_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fall',
            name='fall_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
