# Generated by Django 4.2.7 on 2024-07-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0021_player_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='designation',
            field=models.CharField(blank=True, choices=[('GK', 'Goalkeeper'), ('RB', 'Right Back'), ('LB', 'Left Back'), ('CB', 'Center Back'), ('DM', 'Defensive Midfielder'), ('CM', 'Central Midfielder'), ('AM', 'Attacking Midfielder'), ('RW', 'Right Winger'), ('LW', 'Left Winger'), ('FW', 'Forward')], max_length=100, null=True),
        ),
    ]
