# Generated by Django 4.2.16 on 2024-11-30 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0021_fall_fall_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fall',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsApp.match'),
        ),
    ]
