# Generated by Django 4.2.16 on 2024-11-30 13:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0022_alter_fall_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatchevents',
            name='time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MatchTimeManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, help_text='The time the match started.', null=True)),
                ('paused_time', models.DurationField(default=datetime.timedelta(0), help_text='The total duration the match was paused.')),
                ('resumed_time', models.DateTimeField(blank=True, help_text='The time the match resumed after a pause.', null=True)),
                ('half_time_interval', models.DurationField(default=datetime.timedelta(seconds=900), help_text='The interval duration at halftime.')),
                ('extra_time', models.DurationField(default=datetime.timedelta(0), help_text='Additional time added to the match.')),
                ('full_time_duration', models.DurationField(default=datetime.timedelta(seconds=5400), help_text='Regular full-time duration of the match.')),
                ('total_elapsed_time', models.DurationField(default=datetime.timedelta(0), help_text='Total elapsed time of the match.')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_manager', to='sportsApp.match')),
            ],
        ),
    ]
