# Generated by Django 4.2.7 on 2024-07-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0022_alter_player_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrequest',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
