# Generated by Django 4.2.16 on 2024-11-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0023_playermatchevents_time_matchtimemanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='match',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='player',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='match',
        ),
        migrations.RemoveField(
            model_name='match',
            name='event',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='matchinterruption',
            name='match',
        ),
        migrations.RemoveField(
            model_name='matchtimemanager',
            name='match',
        ),
        migrations.RemoveField(
            model_name='playermatchevents',
            name='match',
        ),
        migrations.RemoveField(
            model_name='playermatchevents',
            name='player',
        ),
        migrations.RemoveField(
            model_name='refree',
            name='event',
        ),
        migrations.RemoveField(
            model_name='refree',
            name='match',
        ),
        migrations.RemoveField(
            model_name='substitution',
            name='match',
        ),
        migrations.RemoveField(
            model_name='substitution',
            name='new_player',
        ),
        migrations.RemoveField(
            model_name='substitution',
            name='previous_player',
        ),
        migrations.RemoveField(
            model_name='substitution',
            name='team',
        ),
        migrations.DeleteModel(
            name='Fall',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='MatchInterruption',
        ),
        migrations.DeleteModel(
            name='MatchTimeManager',
        ),
        migrations.DeleteModel(
            name='PlayerMatchEvents',
        ),
        migrations.DeleteModel(
            name='Refree',
        ),
        migrations.DeleteModel(
            name='Substitution',
        ),
    ]
