# Generated by Django 4.2.16 on 2024-12-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0024_remove_goal_match_remove_goal_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_playing',
            field=models.BooleanField(default=False),
        ),
    ]
