# Generated by Django 4.2.7 on 2024-07-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0024_alter_teamrequest_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamrequest',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
