# Generated by Django 4.2.16 on 2024-12-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0025_player_is_playing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='designation',
            field=models.CharField(blank=True, choices=[('GK', 'Goal_Keeper'), ('LCB', 'Defense Center-Left'), ('RCB', 'Defense Center-Right'), ('LB', 'Defense Left'), ('RB', 'Defense Right'), ('LM', 'Middle Left'), ('RM', 'Middle Right'), ('RW', 'Front Right'), ('LW', 'Front Left'), ('LCF', 'Front Center-Left'), ('RCF', 'Front Center-Right')], max_length=100, null=True),
        ),
    ]
