# Generated by Django 4.2.16 on 2025-01-09 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0027_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamrequest',
            name='total_players',
        ),
    ]
