# Generated by Django 4.2.7 on 2024-07-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0027_team_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='short_name',
        ),
    ]
