# Generated by Django 4.2.16 on 2025-01-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0028_remove_teamrequest_total_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
