# Generated by Django 4.2.7 on 2024-07-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0028_remove_team_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
