# Generated by Django 4.2.16 on 2025-01-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0030_team_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='team',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.RemoveField(
            model_name='pointtable',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='district',
        ),
        migrations.RemoveField(
            model_name='team',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='team',
            name='province',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teamdesign',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teamowner',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teamstatus',
            name='team',
        ),
        migrations.RemoveField(
            model_name='matchstatus',
            name='game',
        ),
    ]
