# Generated by Django 4.2.7 on 2024-08-18 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0030_alter_team_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponser',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sportsApp.event'),
        ),
        migrations.AlterField(
            model_name='sponser',
            name='sponser_type',
            field=models.CharField(choices=[('PLATFORM_SPONSERS', 'platform'), ('EVENT_SPONSERS', 'event')], max_length=25),
        ),
    ]
