# Generated by Django 4.2.7 on 2024-08-20 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0031_alter_sponser_event_alter_sponser_sponser_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('place', models.CharField(max_length=255)),
                ('match_complete', models.BooleanField(default=False)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tiesheet',
            name='match_complete',
        ),
        migrations.RemoveField(
            model_name='tiesheet',
            name='match_date',
        ),
        migrations.RemoveField(
            model_name='tiesheet',
            name='place',
        ),
        migrations.RemoveField(
            model_name='tiesheet',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='tiesheet',
            name='team2',
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('LEAGUE', 'League'), ('KNOCKOUT', 'Knockout'), ('FRIENDLY', 'Friendly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='matchstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='playerstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='playerstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='recentevents',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='recentevents',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_emergency_substitution', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sportsApp.match')),
                ('new_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_player_substitutions', to='sportsApp.player')),
                ('previous_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_player_substitutions', to='sportsApp.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsApp.team')),
            ],
        ),
        migrations.CreateModel(
            name='Refree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('LEFT_TOUCH_LINE', 'Left Touch Line'), ('RIGHT_TOUCH_LINE', 'Right Touch Line'), ('MAIN', 'Main'), ('OUTSIDE', 'Outside')], max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/refree/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sportsApp.event')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sportsApp.match')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMatchEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.CharField(choices=[('FREEKICK', 'FreeKick'), ('CORNER', 'Corner'), ('PENALTY', 'Penalty'), ('OFFSIDE', 'Offside'), ('INJURY', 'Injury')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sportsApp.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsApp.player')),
            ],
        ),
        migrations.CreateModel(
            name='MatchInterruption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interrupted_date', models.DateTimeField()),
                ('cause', models.CharField(choices=[('weather', 'Weather Conditions'), ('injury', 'Player Injury'), ('equipment', 'Equipment Failure'), ('crowd', 'Crowd Disturbance'), ('technical', 'Technical Issue'), ('other', 'Other')], max_length=50)),
                ('duration', models.DateTimeField()),
                ('resumed_date', models.DateTimeField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsApp.match')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsApp.event'),
        ),
        migrations.AddField(
            model_name='match',
            name='man_of_match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sportsApp.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='sportsApp.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='sportsApp.team'),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_description', models.CharField(max_length=255)),
                ('goal_type', models.CharField(choices=[('NORMAL', 'Normal'), ('PENALTY', 'Penalty'), ('FREEKICK', 'Freekick'), ('CORNER', 'Corner')], default='NORMAL', max_length=20)),
                ('goal_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sportsApp.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsApp.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsApp.team')),
            ],
        ),
        migrations.CreateModel(
            name='Fall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fall_type', models.CharField(choices=[('NORMAL', 'Normal'), ('RED_CARD', 'Red Card'), ('YELLOW_CARD', 'Yellow Card')], max_length=20)),
                ('fall_description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sportsApp.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsApp.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsApp.team')),
            ],
        ),
    ]
