# Generated by Django 4.2.16 on 2025-01-09 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('matchApp', '0022_alter_fall_player_alter_goal_player_and_more'),
        ('sportsApp', '0031_remove_coach_team_remove_player_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
        migrations.AlterField(
            model_name='matchstatus',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_match', to='team.team'),
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='PointTable',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamDesign',
        ),
        migrations.DeleteModel(
            name='TeamOwner',
        ),
        migrations.DeleteModel(
            name='TeamStatus',
        ),
    ]
