# Generated by Django 4.2.7 on 2024-08-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0033_guest_eventmembers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventMembers',
            new_name='EventMember',
        ),
    ]
