# Generated by Django 4.2.7 on 2024-08-22 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0036_event_email_event_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='email',
        ),
        migrations.RemoveField(
            model_name='event',
            name='phone',
        ),
    ]
