# Generated by Django 4.2.7 on 2024-08-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0039_eventrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequest',
            name='event_budget',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
    ]
