# Generated by Django 4.2.7 on 2024-08-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0040_eventrequest_event_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponser',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
