# Generated by Django 4.2.7 on 2024-08-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0042_eventteam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerStatus',
        ),
    ]
