# Generated by Django 4.2.7 on 2024-08-22 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0044_remove_match_event_match_event_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='event_team',
        ),
        migrations.AddField(
            model_name='match',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sportsApp.event'),
        ),
    ]
