# Generated by Django 4.2.7 on 2024-08-22 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0046_alter_match_team1_alter_match_team2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='man_of_match',
        ),
    ]
