# Generated by Django 4.2.7 on 2024-08-22 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0047_remove_match_man_of_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('EVENT_REGISTRATION_PAYMENT', 'event payment'), ('TEAM_REGISTRATION_PAYMENT', 'Team Registration payment'), ('EVENT_MEMBER_PAYMENT', 'Event Member Payment'), ('WIN_TEAM_PAYMENT', 'Winning Team Payment'), ('PLAYER_PAYMENT', 'PLAYER PAYMENT'), ('OTHERS', 'others')], max_length=50)),
                ('mobile_number', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_uuid', models.CharField(max_length=255)),
                ('product_code', models.CharField(max_length=255)),
                ('ref_id', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='sportsApp.payment')),
            ],
        ),
    ]
