# Generated by Django 4.2.7 on 2024-08-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0049_remove_payment_email_remove_payment_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='delivery_charge',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='service_charge',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tax_amount',
        ),
    ]
