# Generated by Django 4.2.7 on 2024-08-23 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sportsApp', '0050_remove_payment_amount_remove_payment_delivery_charge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('EVENT_REGISTRATION_PAYMENT', 'event payment'), ('TEAM_REGISTRATION_PAYMENT', 'Team Registration payment'), ('EVENT_MEMBER_PAYMENT', 'Event Member Payment'), ('WIN_TEAM_PAYMENT', 'Winning Team Payment'), ('PLAYER_PAYMENT', 'PLAYER PAYMENT'), ('OTHERS', 'others')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
