# Generated by Django 4.2.7 on 2024-08-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0052_remove_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_uuid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
