# Generated by Django 4.2.7 on 2024-08-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0054_alter_transaction_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_uuid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
