# Generated by Django 4.2.16 on 2024-09-07 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0057_eventorganizer_event_event_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmember',
            name='event',
        ),
        migrations.AddField(
            model_name='eventmember',
            name='event_organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sportsApp.eventorganizer'),
        ),
    ]
