# Generated by Django 4.2.16 on 2024-09-09 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sportsApp', '0058_remove_eventmember_event_eventmember_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorganizer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventorganizer',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/banner/'),
        ),
        migrations.AddField(
            model_name='eventorganizer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/events/'),
        ),
        migrations.AlterField(
            model_name='eventorganizer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to=settings.AUTH_USER_MODEL),
        ),
    ]
