# Generated by Django 4.2.16 on 2024-09-10 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0062_remove_event_email_remove_event_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sportsApp.eventorganizer'),
        ),
    ]
