# Generated by Django 4.2.16 on 2024-09-11 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0063_alter_event_event_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='sportsApp.event'),
        ),
    ]
