# Generated by Django 4.2.16 on 2024-09-15 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0070_eventmemberrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmember',
            name='description',
        ),
        migrations.RemoveField(
            model_name='eventmember',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='eventmember',
            name='event_organizer',
        ),
        migrations.RemoveField(
            model_name='eventmember',
            name='name',
        ),
        migrations.RemoveField(
            model_name='eventmember',
            name='payment',
        ),
        migrations.AddField(
            model_name='eventmember',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventmember',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventmember',
            name='organizer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sportsApp.eventorganizer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventmember',
            name='phone',
            field=models.CharField(default=9865382929, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventmember',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sportsApp.eventmemberrole'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventmember',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
