# Generated by Django 4.2.16 on 2024-09-18 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0071_remove_eventmember_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponser',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/sponsers/'),
        ),
        migrations.AlterField(
            model_name='eventorganizer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eventorganizer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sponser',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sportsApp.eventorganizer'),
        ),
    ]
