# Generated by Django 4.2.16 on 2024-09-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0072_sponser_banner_alter_eventorganizer_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventorganizer',
            name='email',
        ),
    ]
