# Generated by Django 4.2.16 on 2024-09-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0073_remove_eventorganizer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='duration',
        ),
        migrations.AddField(
            model_name='event',
            name='default_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='match_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
