# Generated by Django 4.2.16 on 2024-09-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0074_remove_match_duration_event_default_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_address_default',
            field=models.BooleanField(default=False),
        ),
    ]
