# Generated by Django 4.2.16 on 2024-09-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0075_match_is_address_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
