# Generated by Django 4.2.16 on 2024-09-30 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0078_teamdesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdesign',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sportsApp.team'),
        ),
    ]
