# Generated by Django 4.2.16 on 2024-10-03 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0082_coach_age_coach_description_coach_email_coach_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'Ab Positive'), ('AB-', 'Ab Negative'), ('O+', 'O Positive'), ('O-', 'O Negative')], max_length=25),
        ),
        migrations.AlterField(
            model_name='player',
            name='designation',
            field=models.CharField(blank=True, choices=[('GK', 'Goalkeeper'), ('RB', 'Right Back'), ('LB', 'Left Back'), ('LCB', 'Left Center Back'), ('RCB', 'Right Center Back'), ('LM', 'Left Midfielder'), ('RM', 'Right Midfielder'), ('RW', 'Right Winger'), ('LW', 'Left Winger'), ('LCF', 'Left Center Forward'), ('RCF', 'Right Center Forward')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='MatchPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsApp.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsApp.player')),
            ],
        ),
    ]
