# Generated by Django 4.2.16 on 2024-10-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0083_player_email_player_phone_alter_player_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchplayers',
            name='designation',
            field=models.CharField(choices=[('GK', 'Goalkeeper'), ('RB', 'Right Back'), ('LB', 'Left Back'), ('LCB', 'Left Center Back'), ('RCB', 'Right Center Back'), ('LM', 'Left Midfielder'), ('RM', 'Right Midfielder'), ('RW', 'Right Winger'), ('LW', 'Left Winger'), ('LCF', 'Left Center Forward'), ('RCF', 'Right Center Forward')], max_length=50),
        ),
    ]
