# Generated by Django 4.2.16 on 2024-11-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsApp', '0084_alter_matchplayers_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_organizers_team',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='MatchPlayers',
        ),
    ]
